Repository volf52/deep-neural-net, pull requests merged in 2020-05, with the labels that each got.

#17 Fine Tuning
  .gitignore
  mlpcode/network.py
  mlpcode/test.py
  mlpcode/utils.py
Labels: enhancement

#16 Binarized Neural Net
  .gitignore
  mlpcode/activation.py
  mlpcode/loss.py
  mlpcode/network.py
  mlpcode/test.py
  mlpcode/utils.py
Labels: bug, enhancement

#19 Cifar-10 and affNIST not finished yet
  mlpcode/data/affnist/readme.txt
  mlpcode/data/cifar-10/readme.txt
  mlpcode/network.py
  mlpcode/test.py
  mlpcode/utils.py
Labels: bug, enhancement

#20 Fixed CIFAR-10
  mlpcode/test.py
  mlpcode/utils.py
Labels: enhancement

#21 Fix loading cp weights using np
  mlpcode/loss.py
  mlpcode/network.py
  mlpcode/test.py
  mlpcode/utils.py
Labels: bug

#22 Add feature - Decaying learning rate
  mlpcode/network.py
  mlpcode/optim.py
  mlpcode/test.py
Labels: enhancement

#23 Update optim.py
  mlpcode/optim.py
Labels: bug

#25 Add support for testing and saving binary versions of the model
  mlpcode/network.py
  mlpcode/optim.py
  mlpcode/test.py
  mlpcode/utils.py
Labels: enhancement

#26 Add quanitzation support while loading the data
  mlpcode/utils.py
  test.py
Labels: enhancement

#27 Fix quantization function
  mlpcode/utils.py
  test.py
Labels: bug

#28 Fix relu
  mlpcode/activation.py
  test.py
Labels: bug

#29 Add support for BNN (second try)
  mlpcode/activation.py
  mlpcode/loss.py
  mlpcode/network.py
  mlpcode/utils.py
  test.py
Labels: enhancement

#30 Refactor layers
  mlpcode/activation.py
  mlpcode/layers.py
  mlpcode/loss.py
  mlpcode/network.py
  mlpcode/utils.py
  test.py
Labels: enhancement

#31 HDF5 for saving/loading models
  mlpcode/layers.py
  mlpcode/network.py
  pyproject.toml
  test.py
Labels: enhancement

#32 Add BatchNorm feature
  mlpcode/layers.py
  mlpcode/network.py
  test.py
Labels: enhancement
